# Generated by Django 5.1 on 2024-09-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musicians',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('instrument_type', models.CharField(choices=[('guitar', 'Guitar'), ('cello', 'Cello'), ('flutes', 'Flutes'), ('piano', 'Piano')], max_length=50)),
            ],
        ),
    ]
