USE DUMMYDB;

SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;

-- without using join syntax how we can join two table
-- WE CAN WRITE THIS ONE TOO

-- SELECT FIRST_NAME,DEPARTMENT_NAME
SELECT EMPLOYEES.FIRST_NAME , DEPARTMENTS.DEPARTMENT_NAME -- THIS ONE IS FOR BEST PRACTICE TO UNDERSTAND
FROM EMPLOYEES, DEPARTMENTS
WHERE EMPLOYEES.DEPARTMENT_ID=DEPARTMENTS.DEPARTMENT_ID;

-- USING JOIN SYNTAX

SELECT EMPLOYEES.FIRST_NAME,DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES 
             JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;
             
SELECT EMPLOYEES.FIRST_NAME,DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES 
             INNER JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;
             
-- SAME AS PREVIOUS ONE...PREVIOUS ONE IS PREFERRABLE ...FOR REDUCING COMPLEXITY TOO
SELECT EMPLOYEES.FIRST_NAME,DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES 
             JOIN DEPARTMENTS USING (DEPARTMENT_ID);
             
-- LEFT JOIN

SELECT EMPLOYEES.FIRST_NAME,DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES 
             LEFT JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;
             
-- RIGHT JOIN

SELECT EMPLOYEES.FIRST_NAME,DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES 
             RIGHT JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;
             
-- CROSS JOIN

SELECT EMPLOYEES.FIRST_NAME, DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES
              CROSS JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;
             
-- SELF JOIN
SELECT M.FIRST_NAME , E.FIRST_NAME
FROM EMPLOYEES AS E
                 JOIN EMPLOYEES AS M
                 ON E.EMPLOYEE_ID = M.MANAGER_ID;
                 
SELECT * FROM EMPLOYEES;

-- SHOW ME THE DEPARTMENT WHERE NO EMPLOYEE IS PRESENT

SELECT DEPARTMENTS.DEPARTMENT_NAME
FROM DEPARTMENTS
              LEFT JOIN EMPLOYEES
              ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
WHERE EMPLOYEES.DEPARTMENT_ID IS NULL;

-- SHOW THE EMPLOYEE SALARY WHO GOT LESS THAN THEIR AVG DEPARTMENT SALARY

SELECT
     EMPLOYEES.FIRST_NAME,
     EMPLOYEES.SALARY,
     ((SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID= EMPLOYEES.DEPARTMENT_ID) - EMPLOYEES.SALARY) AS SHORTEST_AMOUNT
FROM EMPLOYEES 
           JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID=DEPARTMENTS.DEPARTMENT_ID;

-- SHOW DEPARTMENT NAME WHOSE MINIMUM SALARY IS GREATER THAN 5000

SELECT DEPARTMENTS.DEPARTMENT_NAME,MIN(SALARY),AVG(SALARY)
FROM EMPLOYEES
            JOIN DEPARTMENTS 
               ON EMPLOYEES.DEPARTMENT_ID=DEPARTMENTS.DEPARTMENT_ID
GROUP BY DEPARTMENTS.DEPARTMENT_ID
HAVING MIN(SALARY) > 5000


             