# Generated by Django 5.1 on 2024-09-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=100)),
                ('task_description', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('task_assign_date', models.DateTimeField()),
                ('categories', models.ManyToManyField(related_name='categories', to='category.taskcategory')),
            ],
        ),
    ]
