/* -------DATABASE DESIGN STRATAGIES------ 

1. TOP DOWN APPROACH  (UPOR TEKE NICHE) -> AGHE MODEL BANABO THEN OI ONUJAYI DATA INSERT KORBO...
   EXAMPLE: 
   (HOSPITAL) DATABASE CREATE KORE OI DATABASE ER MODEL JMN (MEDICINE,DOCTOR,PATIENT,PRESCRIPTION) BANABO..
   
2. BOTTOM UP (UPOR TEKE NICH)-> TOP DOWN APPROACH ER OPPOSITE

***DATABASE DESIGN KORTE REQUIREMENT ANALYSIS KORTE HOBE...

WHAT TO AVOID
-------------
1.REDUNDENCY(DUPLICATE) -> UNNECESSARY JINIS RAKHA JABENA.... STUDENT TABLE R RESULT TABLE E SAME FIELD SAME DATA ACHE....OIRKM CREATE KORA JBENBA...KARON CHANGE KORTE GELE JAMELA HOBE

2.INCOMPLETENESS -> STUDENT         RESULT
		         ROLL    NAME     ROLL    GPA
                 1       A         1      5
                 2       B         2      4.55
                 3       C         3      4.80
                                   4       4.89
                                   
INCOMPLETE TABLE AND RELATION BETWEEN STUDENT AND RESULT

