/*    ERD ->ENTITY RELATIONSHIP DIAGRAM

-ENTITY MEANS TABLE OF DATABASE
-RELATION WILL BE TABLE...BUT CANNOT BE ENTITY
- SUPPOSE
       1. STUDENT IS A TABLE...THAT STUDENT TABLE WILL BE ENTITY NAME
       2. STUDENT TABLE'S ELEMENT WILL BE ATTRIBUTES
       
       
       
ENTITY NAME |     RELATION    | ENTITY NAME 
ATTRIBUTE   |                 | ATTRIBUTE

