/* ERD EXAMPLES

SHOPPING MALL
BUY ->
      CHOOSE
	  COUNTER
      CASHER
      BILL GOODS
      PAYMENT

ENTITIES ->
          PRODUCT
          CUSTOMER
          INVOICE/BILL
          CASHIER
          COMPANY
          

PRODUCT TABLE
PR_ID
PR_NAME
PR_PRICE


CUSTOMER TABLE
CU_ID
CU_NAME
CU_PHONE


CASHIER TABLE
CASH_ID
CASH_NAME
CASH_DESIGNATION



COMPANY TABLE
COM_ID
COM_NAME
COM_TYPE


BILL TABLE
BILL_ID
QUANTITY
TOTAL_PRICE
DISCOUNT


- PRODUCT TABLE AND CUSTOMER TABLE RELATION WILL BE BUY...PRODUCT ONEK DITE PARE TAHOLE COMPLEXITY HBE O(N)PRODUCT TABLE ER..R CUSTOMER EKTA KINTE PARE TAHOLE COMPLEXITY HBE O(1)
- BETWEEN COMPANY AND PRODUCT RELATION WILL BE BELONGS...COMPANY 1TA TEKE ASLE PRODUCT THEN COMPLEXITY HBE O(1)...PRODUCT BESIO NITE PARE KOM O NITE PARE TAI COMPLEXITY HBE O(N)
- BETWEEN CASHIER AND BILL RELATION WILL BE MAKE..CASHIER O(1)...BILL O(N)...
- BETWEEN  BILL AND CUSTOMER RELATION WILL BE OWN... 

