/* ERD GENERALIZATIONS 

SCHOOL ---> 1.STUDENT  |
			2.TEACHER  | GENERALIZED PERSON
            3.STUFF    |
            
- HERE TEACHER AND STUFFS ARE GENERALIZED EMPLOYEE
- STUDENT TO PERSON WILL BE GENERALIZATIONS AND FROM PERSON TO STUDENT WILL BE SPECIALIZATION
- SAME AS EMPLOYEE TO TEACHER AND STUFFS WILL BE SPECIALIZATIONS

- from down to top will be generalization
- from top to down will be specialization