-- In this course, which topic you found most interesting. Explain the topic in short and why you found it most interesting?

-- THE VISUAL REPRESENTAION OF DATABASE IS ERD...WHICH IS INTERESTING PART MOST BECAUSE IT HELPS US TO THINK VISUALLY BEFORE EXECUTE OUR DATABASE ON SPECIFIC PROJECT..IT ALSO HELPS US TO EXAMINE OUR COMPLEXITY LEVEL SO THAT WE CAN DO OUR WORK SMARTLY WITHOUT FACING ANY PROBLEM....

