# Generated by Django 5.1 on 2024-09-15 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0003_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_received', to='accounts.userbankaccount'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_sent', to='accounts.userbankaccount'),
        ),
    ]
